<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FarmingSimulatorSDKClient\FarmingSimulatorSDKClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FarmingSimulatorTelemetry.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>